"""LLM verification of rule-based recommendations."""

from __future__ import annotations

import json
import logging

from rag_adviser.llm.client import LLMClient
from rag_adviser.models import LLMVerification, Recommendations, UserAnswers

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """\
You are an expert RAG systems architect. You will review a set of rule-based \
recommendations for a Retrieval-Augmented Generation system configuration. \
The recommendations were generated by an automated tool based on user inputs.

Your job:
1. Assess whether each recommendation is appropriate for the stated scenario.
2. Note any recommendations you agree with and briefly explain why.
3. Suggest refinements or alternatives where you see issues.
4. Flag any additional considerations the user should be aware of.

Respond in JSON format with these exact keys:
{
  "summary": "2-3 sentence overall assessment",
  "agreements": ["list of things the recommendations got right"],
  "refinements": ["list of suggested changes with reasoning"],
  "additional_considerations": ["list of extra things to consider"]
}

Respond ONLY with valid JSON. No markdown fences, no extra text."""


class RecommendationVerifier:
    """Sends rule-based recommendations to an LLM for verification."""

    def __init__(self, client: LLMClient) -> None:
        self._client = client

    def verify(
        self, answers: UserAnswers, recommendations: Recommendations
    ) -> LLMVerification:
        """Verify recommendations using an LLM and return structured feedback."""
        user_prompt = self._build_prompt(answers, recommendations)
        raw = self._client.complete(SYSTEM_PROMPT, user_prompt)

        verification = LLMVerification(
            provider=self._client.config.provider.value,
            model=self._client.config.model,
            raw_response=raw,
        )

        # Parse JSON response
        try:
            # Strip markdown fences if present
            text = raw.strip()
            if text.startswith("```"):
                text = text.split("\n", 1)[1]
                if text.endswith("```"):
                    text = text[:-3]
            data = json.loads(text)
            verification.summary = data.get("summary", "")
            verification.agreements = data.get("agreements", [])
            verification.refinements = data.get("refinements", [])
            verification.additional_considerations = data.get(
                "additional_considerations", []
            )
        except (json.JSONDecodeError, AttributeError):
            # Fall back to raw response as summary
            verification.summary = raw[:500]
            logger.warning("Failed to parse LLM verification as JSON")

        return verification

    def _build_prompt(
        self, answers: UserAnswers, recs: Recommendations
    ) -> str:
        """Build the user prompt with all context for verification."""
        parts = ["## User Scenario\n"]

        parts.append(f"- Use case: {answers.use_case.value}")
        parts.append(
            f"- Deployment: {answers.constraints.environment.value}"
        )
        parts.append(f"- Hardware: {answers.constraints.hardware.value}")
        parts.append(f"- RAM: {answers.constraints.ram_gb}GB")
        if answers.constraints.vram_gb > 0:
            parts.append(f"- VRAM: {answers.constraints.vram_gb}GB")
        parts.append(
            f"- Latency: {answers.constraints.latency_budget.value}"
        )
        parts.append(f"- Privacy: {answers.constraints.privacy.value}")
        parts.append(f"- Budget: {answers.constraints.budget.value}")
        parts.append(f"- Query type: {answers.query_type.value}")
        parts.append(f"- Query complexity: {answers.query_complexity.value}")
        parts.append(
            f"- Expected answer type: {answers.expected_answer_type.value}"
        )
        parts.append(
            f"- Update frequency: {answers.update_frequency.value}"
        )

        if answers.document_stats:
            stats = answers.document_stats
            parts.append("\n## Document Corpus")
            parts.append(f"- Files: {stats.total_files}")
            parts.append(f"- Total tokens (estimated): {stats.total_tokens:,}")
            parts.append(f"- Primary language: {stats.primary_language}")
            parts.append(
                f"- Content type: {stats.detected_content_type.value}"
            )

        parts.append("\n## Recommendations\n")

        if recs.approach:
            parts.append(
                f"### Approach: {recs.approach.recommended_approach.value}"
            )
            parts.append(f"Reasoning: {recs.approach.reasoning}")
            parts.append("")

        if recs.embedding_models:
            top = recs.embedding_models[0]
            parts.append(f"### Embedding Model: {top.model_id}")
            parts.append(
                f"dim={top.dimension}, max_tokens={top.max_tokens}, "
                f"size={top.estimated_size_gb}GB, "
                f"multilingual={top.multilingual}"
            )
            if top.reasons:
                parts.append(f"Reasons: {'; '.join(top.reasons)}")
            parts.append("")

        if recs.chunking:
            c = recs.chunking
            parts.append(f"### Chunking: {c.strategy}")
            parts.append(
                f"size={c.chunk_size}, overlap={c.chunk_overlap}, "
                f"count_by={c.count_by}"
            )
            parts.append("")

        if recs.vector_db:
            parts.append(f"### Vector DB: {recs.vector_db.provider}")
            parts.append(f"Reason: {recs.vector_db.reason}")
            parts.append("")

        if recs.retrieval:
            r = recs.retrieval
            parts.append("### Retrieval Settings")
            parts.append(
                f"top_k={r.top_k}, threshold={r.similarity_threshold}, "
                f"rerank={r.rerank}, strategy={r.prompt_strategy}, "
                f"temperature={r.temperature}"
            )
            parts.append("")

        if recs.query_transformation and recs.query_transformation.techniques:
            techniques = ", ".join(
                t["name"] for t in recs.query_transformation.techniques
            )
            parts.append(f"### Query Pipeline: {techniques}")
            parts.append("")

        if recs.warnings:
            parts.append("### Warnings")
            for w in recs.warnings:
                parts.append(f"- {w}")

        return "\n".join(parts)
